# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-06 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_userprofile_aadhar_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor_services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('price', models.IntegerField()),
                ('seats_count', models.IntegerField()),
                ('vehicle_no', models.CharField(max_length=20)),
                ('transport_mode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(blank=True, max_length=30)),
                ('picture', models.ImageField(blank=True, upload_to='vendor_images')),
                ('gender', models.CharField(choices=[('0', 'Female'), ('1', 'Male'), ('2', 'Other')], max_length=6)),
                ('contact', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=30)),
                ('aadhar_no', models.BigIntegerField(unique=True)),
                ('type', models.CharField(choices=[('Local Transport', 'Local Transport'), ('Teacher', 'Teacher'), ('Car Pool', 'Car Pool'), ('Taxi', 'Taxi'), ('Logistics', 'Logistics'), ('School Bus', 'School Bus')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='aadhar_no',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
