# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-06 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20180406_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_services',
            name='hop_bml',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor_services',
            name='hop_iffco_chowk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor_services',
            name='hop_manesar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor_services',
            name='hop_rajiv_chowk',
            field=models.BooleanField(default=False),
        ),
    ]
