# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-06 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20180406_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('seats_need', models.IntegerField()),
                ('source', models.CharField(choices=[('BML', 'BML'), ('Manesar', 'Manesar'), ('Rajiv Chowk', 'Rajiv Chowk'), ('Iffco Chowk', 'Iffco Chowk')], max_length=15)),
                ('destination', models.CharField(choices=[('BML', 'BML'), ('Manesar', 'Manesar'), ('Rajiv Chowk', 'Rajiv Chowk'), ('Iffco Chowk', 'Iffco Chowk')], max_length=15)),
                ('service_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=6),
        ),
        migrations.AlterField(
            model_name='vendor_services',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=6),
        ),
    ]
