# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-06 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20180406_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_services',
            name='service_id',
            field=models.IntegerField(blank=True),
        ),
    ]
