# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-06 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_auto_20180407_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_services',
            name='service_id',
        ),
        migrations.AddField(
            model_name='user_services',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_services',
            name='seats_count',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_services',
            name='transport_mode',
            field=models.CharField(default='Car', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_services',
            name='vehicle_no',
            field=models.CharField(default='Ax', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_services',
            name='vendor_username',
            field=models.CharField(default='abcd', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor_services',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
